# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year-:month-:day/:title.html
relative_permalinks: false

# Setup
title:               ulf.gjerdingen
tagline:             ...
description:         "c'est le moi..."
url:                 ''
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              ulf gjerdingen
  url:               https://twitter.com/ulfgj
  email:             pagehead@gmail.com

# Custom vars
version:             1.0.1

exclude:
  - tmp/
